/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GuideDocIdRouteImport } from './routes/guide.$docId'
import { Route as LearnUnitIdRouteImport } from './routes/learn.$unitId'
import { Route as ReadDocIdRouteImport } from './routes/read.$docId'
import { Route as ReferenceIndexRouteImport } from './routes/reference.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideDocIdRoute = GuideDocIdRouteImport.update({
  id: '/guide/$docId',
  path: '/guide/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnUnitIdRoute = LearnUnitIdRouteImport.update({
  id: '/learn/$unitId',
  path: '/learn/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadDocIdRoute = ReadDocIdRouteImport.update({
  id: '/read/$docId',
  path: '/read/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceIndexRoute = ReferenceIndexRouteImport.update({
  id: '/reference/',
  path: '/reference/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/guide/$docId': typeof GuideDocIdRoute
  '/learn/$unitId': typeof LearnUnitIdRoute
  '/read/$docId': typeof ReadDocIdRoute
  '/reference/': typeof ReferenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/guide/$docId': typeof GuideDocIdRoute
  '/learn/$unitId': typeof LearnUnitIdRoute
  '/read/$docId': typeof ReadDocIdRoute
  '/reference': typeof ReferenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/guide/$docId': typeof GuideDocIdRoute
  '/learn/$unitId': typeof LearnUnitIdRoute
  '/read/$docId': typeof ReadDocIdRoute
  '/reference/': typeof ReferenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/guide/$docId'
    | '/learn/$unitId'
    | '/read/$docId'
    | '/reference/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/guide/$docId'
    | '/learn/$unitId'
    | '/read/$docId'
    | '/reference'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/guide/$docId'
    | '/learn/$unitId'
    | '/read/$docId'
    | '/reference/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  GuideDocIdRoute: typeof GuideDocIdRoute
  LearnUnitIdRoute: typeof LearnUnitIdRoute
  ReadDocIdRoute: typeof ReadDocIdRoute
  ReferenceIndexRoute: typeof ReferenceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$docId': {
      id: '/guide/$docId'
      path: '/guide/$docId'
      fullPath: '/guide/$docId'
      preLoaderRoute: typeof GuideDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$unitId': {
      id: '/learn/$unitId'
      path: '/learn/$unitId'
      fullPath: '/learn/$unitId'
      preLoaderRoute: typeof LearnUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$docId': {
      id: '/read/$docId'
      path: '/read/$docId'
      fullPath: '/read/$docId'
      preLoaderRoute: typeof ReadDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/': {
      id: '/reference/'
      path: '/reference'
      fullPath: '/reference/'
      preLoaderRoute: typeof ReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  GuideDocIdRoute: GuideDocIdRoute,
  LearnUnitIdRoute: LearnUnitIdRoute,
  ReadDocIdRoute: ReadDocIdRoute,
  ReferenceIndexRoute: ReferenceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
